import type { Theme } from "./contract.js";

export const lightTheme = {
  id: "light",
  name: "Light",
  appearance: "light",
  colors: {
    "app-background": "#f5f5f5",
    "sidebar-background": "rgb(235 235 235 / 92%)",
    "inspector-background": "#eeeeee",
    "composer-background": "#ffffff",
    "card-background": "#eeeeee",
    "hover-background": "#e5e5e5",
    "selected-background": "#dddddd",
    "control-background": "#d7d7d7",
    "border-default": "#d0d0d0",
    "border-focus": "#858585",
    "text-primary": "#242424",
    "text-strong": "#111111",
    "text-secondary": "#424242",
    "text-muted": "#666666",
    "text-faint": "#7a7a7a",
    accent: "#181818",
    "accent-contrast": "#ffffff",
    "status-info-text": "#174f78",
    "status-info-background": "#dceefa",
    "status-success-text": "#1f6637",
    "status-success-background": "#dcefe2",
    "status-warning-text": "#795018",
    "status-warning-background": "#f5e8cf",
    "status-danger-text": "#8f2d2d",
    "status-danger-background": "#f4dddd",
    "message-danger-background": "#f8e6e6",
    "unsafe-text": "#75502f",
    "unsafe-indicator": "#a96528",
    "code-background": "#1f1f1f",
    "code-text": "#e4e4e4",
    "syntax-comment": "#9aa4ad",
    "syntax-keyword": "#ff7b72",
    "syntax-string": "#a5d6ff",
    "syntax-number": "#79c0ff",
    "syntax-function": "#d2a8ff",
    "syntax-type": "#ffa657",
    "syntax-operator": "#c9d1d9",
    "diff-added-text": "#1f6637",
    "diff-added-background": "#dcefe2",
    "diff-removed-text": "#8f2d2d",
    "diff-removed-background": "#f4dddd",
    "diff-modified-text": "#795018",
    "diff-modified-background": "#f5e8cf",
  },
} satisfies Theme;
